apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-listener
  namespace: service-demonstrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app-listener
  template:
    metadata:
      labels:
        app: go-app-listener
    spec:
      containers:
      - name: go-app-listener
        image: go-listener:1.1
        ports:
        - name: http
          containerPort: 8090